services:
  mysql_test:
    image: mysql:8.0
    command: --default-time-zone=SYSTEM
    container_name: mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5599
      MYSQL_DATABASE: cinephoria_test
    ports:
      - "3307:3306"                        # Different port to avoid conflicts
    volumes:
      - mysql_test_data:/var/lib/mysql     # Separate volume for test data

  redis_test:
    image: redis:7.0-alpine
    container_name: redis_test
    restart: always
    ports:
      - "6380:6379"                        # Different port to avoid conflicts
    volumes:
      - redis_test_data:/data

  test_runner:
    build:
      context: ./server
    container_name: test_runner
    restart: "no"
    env_file:
      - ./server/.test.env
    environment:
      MYSQL_HOST: mysql_test
      REDIS_HOST: redis_test
    depends_on:
      - mysql_test
      - redis_test
    command: |
      sh -c "
        echo 'Waiting 30 seconds for services to be fully ready...'
        sleep 30
        echo 'Starting test suite...'
        npm run test
        echo 'Test suite completed!'
      "

volumes:
  mysql_test_data:    # Separate volume for test MySQL data
  redis_test_data:    # Separate volume for test Redis data  
  node_modules_test:  # Separate volume for test node_modules