services:
  mysql:
    image: mysql:8.0
    command: --default-time-zone=SYSTEM
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5599
      MYSQL_DATABASE: cinephoria
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: ./server
    container_name: backend_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: npm start

  client:
    build:
      context: ./client
    container_name: frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm start

volumes:
  mysql_data:
